[project]
name = "user-agent-search-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fake-headers>=1.0.2",
    "requests>=2.32.5",
]
